#!/bin/bash
cd REST
c=$(nproc)
if [ $# -gt 0 ]; then
	c=$1
fi
celery -A tasks worker --concurrency=$c --loglevel=info

#To run multiple workers:
#cd REST
#celery -A tasks worker --concurrency=1 --loglevel=info -n wkr1@yuvi-grp7-benchop #this one runs one worker with name wkr1@yuvi-grp7-benchop and spawns 1 child process
#celery -A tasks worker --concurrency=2 --loglevel=info -n wkr2@yuvi-grp7-benchop #one worker wkr2@yuvi-grp7-benchop runs in sync with wkr1@yuvi-grp7-benchop and spawns 2 parallel child processes

